New styre approved 2024-11-05
fribyte-code/fribyte.no pull request #123
Opened 2024-11-12 18:19 UTC by skivdal

To be merged on 2024-12-01 if LGTM

2024-11-12 18:32 UTC, simsine requested changes
Annet en  min  egen epost så  LGTM :+1:

2024-11-12 18:32 UTC, simsine commented on content/kontakt/members.json
> +    "email": "zimen@fribyte.no",
La til en identitet til migadu eposten, så vil gjerne bruke den istedet.
```suggestion
    "email": "simen.stromsnes@fribyte.no",
```

2024-11-12 18:34 UTC, skivdal commented
Perfectomento!

2024-11-12 18:35 UTC, simsine approved these changes

2024-11-13 14:40 UTC, mathiash98 approved these changes

2024-11-30 23:27 UTC, merged

2024-11-30 23:27 UTC, skivdal commented
:partying_face: