:lipstick: reverserer frontside tilbake til standard
fribyte-code/fribyte.no pull request #56
Opened 2024-01-05 11:43 UTC by SindreKjelsrud

2024-01-05 11:54 UTC, timharek requested changes
Nice! 👌  Dette hadde jeg helt glemt ut 😅 

Vil heller foreslå å bruke Tera-template sine comments, istedenfor HTML:
https://keats.github.io/tera/docs/#comments

HTML-kommentarene vil alltid være der i nettleseren

2024-01-06 09:26 UTC, SindreKjelsrud commented
@timharek ser dette mer riktig ut? hehe første gang jeg prøver meg på Tera :sweat_smile:

2024-01-08 23:07 UTC, timharek approved these changes
Knall – enda bedre! 🎩 

Hadde en pitte liten knirk, men ikke noe spes å tenke på 😊

2024-01-08 23:07 UTC, timharek commented on templates/index.html
> +      </div>
```suggestion
      <div id="banner"></div>
```

2024-01-09 13:41 UTC, polsevev approved these changes
LGTM!

2024-01-09 16:51 UTC, mathiash98 approved these changes
LGTM!

2024-01-09 19:05 UTC, merged